delivery/urls.py
from django.conf.urls import url
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from delivery.views import *

urlpatterns = [
    # front page
    url(r'^$', 'delivery.views.delivery_list'),

    # Delivery URLs
    url(r'^delivery$', 'delivery.views.delivery_list'),
    url(r'^delivery/all$', 'delivery.views.delivery_list_all'),
    # url(r'^delivery/new$', DeliveryListView.as_view(), {'deleted': False}),
    url(r'^delivery/add_update$', 'delivery.views.delivery_add_update'),
    url(r'^delivery/delete', 'delivery.views.delivery_delete'),
    url(r'^delivery/detail/(?P<delivery_id>[\w-]+)', 'delivery.views.delivery_detail'),
    url(r'^delivery/detail_print/(?P<delivery_id>[\w-]+)', 'delivery.views.delivery_detail_print'),

    # url(r'^delivery/detail_taken', 'delivery.views.delivery_detail_taken'),
    url(r'^delivery/taken', 'delivery.views.delivery_taken'),
    url(r'^delivery/check', 'delivery.views.delivery_check'),
    url(r'^delivery/feedback', 'delivery.views.delivery_feedback'),

    #PhonePrice Summary
    url(r'^price_summary$', 'delivery.views.price'),

    #PhonePrice
    url(r'^price$', ListView.as_view(model=PhonePrice), name="price_list"),
    url(r'^price/detail/(?P<pk>[\w-]+)',
        UpdateView.as_view(model=PhonePrice, fields=['phone_type', 'group', 'phone_status', 'process_type', 'price'],
                           template_name_suffix="_detail", success_url='/price'), name="price_detail"),
    url(r'^price/add',
        CreateView.as_view(model=PhonePrice, fields=['phone_type', 'group', 'phone_status', 'process_type', 'price'],
                           template_name_suffix="_detail", success_url='/price'), name="price_add"),
    url(r'^price/delete/(?P<pk>[\w-]+)',
        DeleteView.as_view(model=PhonePrice, template_name_suffix="_confirm_delete", success_url='/price'),
        name="price_delete"),

    #PhoneType
    url(r'^phone$', ListView.as_view(model=PhoneType), name="phone_type_list"),
    url(r'^phone/detail/(?P<pk>[\w-]+)',
        UpdateView.as_view(model=PhoneType, fields=['name', 'swap_default_price', 'buyback_default_price'],
                           template_name_suffix="_detail", success_url='/phone'), name="phone_type_detail"),
    url(r'^phone/add',
        CreateView.as_view(model=PhoneType, fields=['name', 'swap_default_price', 'buyback_default_price'],
                           template_name_suffix="_detail", success_url='/phone'), name="phone_type_add"),

    #PaymentInfo
    url(r'^payment$', ListView.as_view(model=PaymentInfo), name="phone_type_list"),
    url(r'^payment/detail/(?P<pk>[\w-]+)',
        UpdateView.as_view(model=PaymentInfo, form_class=PaymentInfoForm, template_name_suffix="_detail",
                           success_url='/payment'), name="phone_type_detail"),
    url(r'^payment/add',
        CreateView.as_view(model=PaymentInfo, fields=['user', 'info'], template_name_suffix="_detail",
                           success_url='/payment'), name="phone_type_add"),
    url(r'^payment/delete/(?P<pk>[\w-]+)',
        DeleteView.as_view(model=PaymentInfo, template_name_suffix="_confirm_delete", success_url='/payment'),
        name="phone_type_delete"),

    #PhoneVariable
    url(r'^phone_var$', ListView.as_view(model=PhoneVariable), name="phone_variable_list"),
    url(r'^phone_var/detail/(?P<pk>[\w-]+)',
        UpdateView.as_view(model=PhoneVariable, fields=['phone_type', 'name'], template_name_suffix="_detail",
                           success_url='/phone_var'), name="phone_variable_detail"),
    url(r'^phone_var/add',
        CreateView.as_view(model=PhoneVariable, fields=['phone_type', 'name'], template_name_suffix="_detail",
                           success_url='/phone_var'), name="phone_variable_add"),
    url(r'^phone_var/delete/(?P<pk>[\w-]+)',
        DeleteView.as_view(model=PhoneVariable, template_name_suffix="_confirm_delete", success_url='/phone_var'),
        name="phone_variable_delete"),

    #DeliveryStatus
    url(r'^delivery_status$', ListView.as_view(model=DeliveryStatus), name="delivery_status_list"),
    url(r'^delivery_status/detail/(?P<pk>\d+)',
        UpdateView.as_view(model=DeliveryStatus, fields=['name'], template_name_suffix="_detail",
                           success_url='/delivery_status'),
        name="delivery_status_detail"),
    url(r'^delivery_status/add',
        CreateView.as_view(model=DeliveryStatus, fields=['name'], template_name_suffix="_detail",
                           success_url='/delivery_status'), name="delivery_status_add"),
    url(r'^delivery_status/delete/(?P<pk>[\w-]+)',
        DeleteView.as_view(model=DeliveryStatus, template_name_suffix="_confirm_delete",
                           success_url='/delivery_status'),
        name="delivery_status_delete"),

]

r2d2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login

urlpatterns = [
    # accounts url
    url(r'^accounts/login/$', login, {'template_name': 'login.html'}),
    url(r'^accounts/', include('django.contrib.auth.urls')),

    # admin url
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('delivery.urls'))
]

delivery/models.py
from django.contrib.auth.models import Group, User
from django.db import models


class PaymentInfo(models.Model):
    user = models.ForeignKey(User)
    info = models.CharField(max_length=200)

    def __unicode__(self):
        return 'PaymentInfo: {}'.format(self.user.username)


class PhoneType(models.Model):
    name = models.CharField(max_length=200)
    swap_default_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    buyback_default_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __unicode__(self):
        return 'PhoneType: {}, {}, {}'.format(self.name, self.swap_default_price, self.buyback_default_price)

    def save(self, *args, **kwargs):
        super(PhoneType, self).save(*args, **kwargs)
        phone_variables = PhoneVariable.objects.filter(phone_type=self)
        if not phone_variables:
            phone_variable = PhoneVariable()
            phone_variable.phone_type = self
            phone_variable.name = 'Any Color'
            phone_variable.save()


class PhoneVariable(models.Model):
    phone_type = models.ForeignKey(PhoneType)
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return 'PhoneVariable: {}, {}'.format(self.name, self.phone_type.name)


# Total_Qualified, Pink_Mark, Non-OEM, Fixable_TP
class PhoneStatus(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return 'PhoneStatus: {}'.format(self.name)


class DeliveryStatus(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return 'DeliveryStatus: {}'.format(self.name)


# Swap, Buyback
class ProcessType(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return 'ProcessType: {}'.format(self.name)


class PhonePrice(models.Model):
    phone_type = models.ForeignKey(PhoneType)
    group = models.ForeignKey(Group)
    phone_status = models.ForeignKey(PhoneStatus)
    process_type = models.ForeignKey(ProcessType)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __unicode__(self):
        return 'PhonePrice: {}, {}, {}, {}'.format(self.phone_type.name, self.group.name, self.phone_status.name,
                                                   self.price)


class Delivery(models.Model):
    user = models.ForeignKey(User)
    delivery_status = models.ForeignKey(DeliveryStatus)
    delivery_company = models.CharField(max_length=200)
    serial = models.CharField(max_length=200)
    start_date = models.DateField()
    receive_date = models.DateField(null=True)
    check_date = models.DateField(null=True)
    deleted = models.BooleanField(default=False)

    def __unicode__(self):
        return '[{}] Delivery({}): {}'.format(self.id, self.serial, self.user.username)


class DeliveryItem(models.Model):
    delivery = models.ForeignKey(Delivery)
    phone_type = models.ForeignKey(PhoneType)
    count = models.IntegerField(default=1)
    received = models.IntegerField(default=0)

    def __unicode__(self):
        return '[{}] Content of Delivery {}: {} {}'.format(self.id, self.delivery.serial, self.phone_type.name,
                                                           self.count)


class CheckResult(models.Model):
    delivery_item = models.ForeignKey(DeliveryItem)
    phone_status = models.ForeignKey(PhoneStatus)
    count = models.IntegerField(default=1)

    def __unicode__(self):
        return '[{}] CheckResult for DeliveryItem({}): {}, {}'.format(self.id, self.delivery_item.id,
                                                                      self.phone_status.name,
                                                                      self.count)


class Response(models.Model):
    check_result = models.ForeignKey(CheckResult)
    phone_variable = models.ForeignKey(PhoneVariable)
    process_count = models.IntegerField(default=1)
    response_date = models.DateTimeField()

    def __unicode__(self):
        return 'Response: ' + self.delivery.serial + ',' + self.phone_type.name + str(self.count)


class Setting(models.Model):
    setting_key = models.CharField(max_length=200)
    setting_value = models.CharField(max_length=200)

    def __unicode__(self):
        return 'Setting: ' + self.setting_key + ',' + self.setting_value

delivery/templates/delivery/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}

    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1">
    -->
    <meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

{#    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}"/>#}
{#    <script src="{% static 'js/jquery-2.1.4.js' %}"></script>#}
{#    <script src="{% static 'js/jquery-ui.min.js' %}"></script>#}
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

    {% block head %}{% endblock %}

    <title>{% block title %}R2D2: Delivery & Fix{% endblock %}</title>
</head>

<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">R2D2</a>
        </div>
        <div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>

                <li><a href="/delivery">Orders</a></li>
                <li><a href="/delivery/add_update">Create Order</a></li>
                {% if request.user.is_superuser %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Configurations
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/price_summary">Price Summary</a></li>
                            <li><a href="/phone">Phone Types</a></li>
                            <li><a href="/phone_var">Phone Variable</a></li>
                            <li><a href="/price">Variable Price</a></li>
                            <li><a href="/payment">Payment Info</a></li>
                            <li><a href="/delivery_status">Delivery Status</a></li>
                        </ul>
                    </li>
                    <li><a href="/admin">Admin</a></li>
                {% endif %}
                <li><a href="/accounts/logout">Logout</a></li>
            </ul>
        </div>
    </div>
</nav>

<div id="content" class="container">
    {% block content %}{% endblock %}
</div>

{#<div id="footer">#}
{#    {% block footer %}{% endblock %}#}
{#    <div style="float:right">R2D2 By YiChen.</div>#}
{#</div>#}
</body>
</html>

delivery/templates/delivery/delivery_detail_print.html
{% extends "delivery/base.html" %}

{% load r2d2_filters %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="well">
                <h2>
                    Order Detail Print Version: # {{ delivery_id }}
                </h2>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h3>Order Detail:</h3>

            <table class="table table-striped table-hover">
                {% for field in delivery_form.visible_fields %}
                    <td>{{ field.label_tag }}</td>
                    <td> {{ field.value }}</td>
                    <tr>
                {% endfor %}
            </table>

            <h3>Received Detail:</h3>

            <table class="table table-striped table-hover">
                {% for field in taken_form.visible_fields %}
                    <td>{{ field.label_tag }}</td>
                    <td> {{ field.value }}</td>
                    <tr>
                {% endfor %}
            </table>

            <h3>Test Result:</h3>

            <table class="table table-striped table-hover" style="text-align:center">
                {{ check_form|check_table_print|safe }}
            </table>

            <h3>Confirm Detail:</h3>

            <table class="table table-hover" style="text-align:center">
                {{ feedback_form|feedback_table_print|safe }}
            </table>
        </div>
    </div>
    </div>
{% endblock %}

delivery/templates/delivery/delivery_list.html
{% extends "delivery/base.html" %}

{% load r2d2_filters %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="well"><h2>Order List</h2></div>
        </div>
    </div>

    <form id="delivery_detail" action="/delivery/all" method="get">
        <button id="form_button" class="btn btn-info">Show all</button>
    </form>

    <p>

    <table class="table table-striped table-hover">
        {% if not object_list %}
            No Delivery Found
        {% else %}
            <tr>
                <th>ID</th>
                <th>User</th>
                <th>Status</th>
                <th>Delivery Company</th>
                <th>Serial</th>
                <th>Date</th>
                <th>Detail</th>
                <th>Action</th>
            </tr>
            {% for delivery in object_list %}
                <tr>
                    <td>
                        <form id="delivery_detail" action="/delivery/detail/{{ delivery.id }}" method="get">
                            {% if delivery.deleted %}
                                <button id="form_button" class="btn btn-danger">{{ delivery.id }}</button>
                            {% else %}
                                <button id="form_button" class="btn btn-info">{{ delivery.id }}</button>
                            {% endif %}
                        </form>
                    </td>
                    <td>{{ delivery.user.username }}</td>
                    <td>{{ delivery.delivery_status.name }}</td>
                    <td>{{ delivery.delivery_company }}</td>
                    <td>{{ delivery.serial }}</td>
                    <td>Start:{{ delivery.start_date }}
                        {% if delivery.receive_date %}
                            <br>Receive:{{ delivery.receive_date }}
                        {% endif %}
                        {% if delivery.check_date %}
                            <br>Check:{{ delivery.check_date }}
                        {% endif %}
                    </td>
                    <td>
                        {% for item in delivery.deliveryitem_set.all %}
                            <br>
                            {{ item.phone_type.name }}: {{ item.count }}
                            {% if item.received > 0 %}
                                , received: {{ item.received }}
                            {% endif %}
                            <br>
                            {% for check_result in item.checkresult_set.all %}
                                <br> {{ check_result.phone_status.name }} : {{ check_result.count }}
                                {% for response in check_result.response_set.all %}
                                    {{ response.phone_variable.name }} : {{ response.process_count }}
                                {% endfor %}
                            {% endfor %}
                            <br>
                        {% endfor %}
                    </td>
                    <td>
                        <form class="button_form" style="vertical-align: middle;margin: 10px" id="delivery_delete"
                              action="/delivery/delete" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="delivery_id" value="{{ delivery.id }}"/>
                            {% if not delivery.deleted %}
                                <button id="form_button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">Hide</button>
                            {% else %}
                                <button id="form_button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">Recover</button>
                            {% endif %}
                        </form>
                    </td>

                </tr>
            {% endfor %}
        {% endif %}
    </table>
{% endblock %}

delivery/templates/delivery/deliverystatus_confirm_delete.html
{% extends "delivery/base.html" %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

delivery/templates/delivery/deliverystatus_detail.html
{% extends "delivery/base.html" %}

{% block content %}
    {% if object %}
        <span class="label label-default">ID:</span> {{ object.id }}
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <br>
        {% if object %}
            <input type="submit" value="Update"/>
        {% else %}
            <input type="submit" value="Create"/>
        {% endif %}
    </form>
{% endblock %}

delivery/templates/delivery/index.html
{% extends "delivery/base.html" %}


{% block content %}
    Hello, This is index page.
{% endblock %}

delivery/templates/delivery/login.html
{% extends "delivery/base.html" %}

{% block content %}

    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
        {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
        {% else %}
            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}

    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="login"/>
        <input type="hidden" name="next" value="{{ next }}"/>
    </form>

    {# Assumes you setup the password_reset view in your URLconf #}
    <p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

delivery/templates/delivery/paymentinfo_confirm_delete.html
{% extends "delivery/base.html" %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

delivery/templates/delivery/paymentinfo_detail.html
{% extends "delivery/base.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if object %}
            <input type="submit" value="Update"/>
        {% else %}
            <input type="submit" value="Create"/>
        {% endif %}
    </form>
{% endblock %}

delivery/templates/delivery/phoneprice_confirm_delete.html
{% extends "delivery/base.html" %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

delivery/templates/delivery/phonetype_detail.html
{% extends "delivery/base.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if object %}
            <input type="submit" value="Update"/>
        {% else %}
            <input type="submit" value="Create"/>
        {% endif %}
    </form>
{% endblock %}

delivery/templates/delivery/phonetype_list.html
{% extends "delivery/base.html" %}

{% block content %}
    <table class="table table-striped table-hover">
        <tr>
            <th></th>
            <th>Name</th>
            <th>Default Repair Price</th>
            <th>Default Sale Price</th>
        </tr>
        {% for phone_type in phonetype_list %}
            <tr>
                <td>
                    <a href="/phone/detail/{{ phone_type.id }}">{{ phone_type.id }}</a>
                </td>
                <td>{{ phone_type.name }}</td>
                <td>{{ phone_type.swap_default_price }}</td>
                <td>{{ phone_type.buyback_default_price }}</td>
            </tr>
        {% endfor %}
    </table>
    <a href="/phone/add">Add Phone Type</a>
{% endblock %}

delivery/templates/delivery/phonevariable_confirm_delete.html
{% extends "delivery/base.html" %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

delivery/templates/delivery/phonevariable_list.html
{% extends "delivery/base.html" %}

{% block content %}
    <table class="table table-striped table-hover">
        <tr>
            <th></th>
            <th>Phone Type</th>
            <th>Variable Name</th>
            <th>Action</th>
        </tr>
        {% for phone_var in phonevariable_list %}
            <tr>
                <td>
                    <a href="/phone_var/detail/{{ phone_var.id }}">{{ phone_var.id }}</a>
                </td>
                <td>{{ phone_var.phone_type.name }}</td>
                <td>{{ phone_var.name }}</td>
                <td>
                    <a href="/phone_var/delete/{{ phone_var.id }}">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="/phone_var/add">Add Phone Variable</a>
{% endblock %}